name: virus_chat_app
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  google_sign_in: ^4.0.7
  shared_preferences: ^0.5.6
#  firebase_auth:  ^0.15.5+3
  cloud_firestore: ^0.13.0+1
  fluttertoast: ^3.1.3
  location: ^2.3.5
  provider: ^3.0.0
  firebase_auth: ^0.15.3
  firebase_messaging: ^5.0.4
  flutter_facebook_login: ^3.0.0
  http: ^0.12.0+2

  flare_splash_screen: ^2.0.1+2
  geoflutterfire : ^2.0.2

  flutter_range_slider: "^1.4.0"
  latlong: ^0.6.1
  photo_view: ^0.5.0
  image_picker: ^0.6.1+8
  firebase_storage: ^3.0.6
  cached_network_image: 2.0.0-rc.1
  country_code_picker: ^1.3.7
  flutter_sound: ^3.0.0    #3.1.7
  flutter_svg: ^0.17.3+1
#  audioplayers: ^0.14.2
#  audio_recorder2: ^1.0.0
  flutter_cache_manager: ^1.1.3
  flutter_local_notifications: ^1.4.0
  device_info: ^0.4.2+1
  mobile_number: ^0.0.4
  flutter_ffmpeg: ^0.2.10





dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

#  plugin:
#    platforms:
#      android:
#        package: com.jeffg.emoji_picker
#        pluginClass: EmojiPickerPlugin
#      ios:
#        pluginClass: EmojiPickerPlugin
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
      - images/splashnew.png
      - images/google.png
      - images/facebook.png
      - images/alert.svg
      - images/camera.svg
      - images/help.svg
      - images/marketplace.svg
      - images/pic.svg
      - images/post_icon.svg
      - images/Send.svg
      - images/smile.svg
      - images/social.svg
      - images/voice.svg
      - images/voice_highlight.svg
      - images/tag_market_place.svg
      - images/tag_alert.svg
      - images/tag_social.svg
      - images/tag_help.svg
      - images/post.svg
      - images/home.svg
      - images/home_highlight.svg
      - images/community.svg
      - images/home_chat.svg
      - images/accept.svg
      - images/image.svg
      - images/phone.svg
      - images/gmail.svg
      - images/fb.svg
      - images/splash.svg
      - images/invite_sent.svg
      - images/logout.svg
      - images/online_idle.svg
      - images/online_active.svg
      - images/online_inactive.svg
      - images/friend_request.svg
      - images/recent_chat.svg
      - images/walkthrough_step1.svg
      - images/walkthrough_step2.svg
      - images/walkthrough_step3.svg
      - images/splash_new.svg
      - images/friend_accept.svg
      - images/friend_decline.svg
      - images/walkthrough_step1_new.png
      - images/walkthrough_step2_new.png
      - images/walkthrough_step3_new.png

  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
